{% set name = "napari-gruvbox" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 303a0340d2932932c155d77a074004d31a307f3e8bafde7946c2ea91a5f41581

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - python >=3.8
    - pygments >=2.9

test:
  imports:
    - napari_gruvbox
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brisvag/napari-gruvbox
  summary: Gruvbox theme for napari.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
