{% set name = "napari-gruvbox" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-gruvbox-{{ version }}.tar.gz
  sha256: 8623bd1a65210daf1c5f1f63f68fdb42a01262202517c24ab4d2ecff27dd93a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - python >=3.8

test:
  imports:
    - napari_gruvbox
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brisvag/napari-gruvbox
  summary: Gruvbox theme for napari.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
